# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: black
      - id: isort
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
      - id: mypy
      - id: vulture
