# .github/workflows/tests.yml
name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - run: sudo apt -y install libeigen3-dev
      - run: cd /usr/include && sudo ln -sf eigen3/Eigen Eigen
      - run: sudo apt -y install ninja-build
      - run: pip install nox==2020.12.31
      - run: pip install poetry==1.1.6
      - run: nox
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: test-pmbm-plots
          path: tests/PMBM/.images/*.png
